on: push
name: Website
jobs:
  web-deploy:
    name: Lanseaza
    runs-on: ubuntu-latest
    steps:
    - name: Obtine ultimele modificari
      uses: actions/checkout@v2
    
    - name: Sincronizeaza fisierele
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.isaidpower.dev
        username: github_isaidpower.dev
        password: ${{ secrets.ftp_password }}
